### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Jason-Humphrey** [Jason-Humphrey/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] Create html, CSS and Javascript files
- [x] connect files
- [x] insert favicon
- [x]  Create game background
- [x]  Insert car Image
- [x]  adjust car image in CSS
- [x] Submit pull request
